// Compiles shared/reasons.v1.json into the TS union and the renderer the client
// uses. One file is the source of truth for all four language bindings.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const src = JSON.parse(readFileSync(resolve(here, "../../shared/reasons.v1.json"), "utf8"));
const codes = src.reasons.map((r) => r.code);
const templates = Object.fromEntries(src.reasons.map((r) => [r.code, r.message_template]));

const body = `// GENERATED by npm run gen:reasons from shared/reasons.v1.json. Do not edit.
export type ReasonCode =
${codes.map((c) => `  | "${c}"`).join("\n")};

const TEMPLATES: Record<ReasonCode, string> = ${JSON.stringify(templates, null, 2)} as Record<ReasonCode, string>;

export const REASON_CODES: ReasonCode[] = ${JSON.stringify(codes)} as ReasonCode[];

/** Renders a deterministic reason. Reason messages are error messages and are
 * the one class of visible string outside the label catalogue. */
export function renderReason(code: string, params: Record<string, unknown>): string {
  const t = TEMPLATES[code as ReasonCode];
  if (!t) return code;
  return t.replace(/\\{(\\w+)\\}/g, (_m, k) => {
    const v = params[k];
    return v === undefined || v === null ? "—" : String(v);
  });
}
`;
writeFileSync(resolve(here, "../src/reasons.generated.ts"), body);
console.log(`reasons: wrote src/reasons.generated.ts (${codes.length} codes)`);
